//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIHub.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("APIHub.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key has been Successfully Activated, .
        /// </summary>
        internal static string ActivationSuccess_MSGBody {
            get {
                return ResourceManager.GetString("ActivationSuccess_MSGBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Successfull!.
        /// </summary>
        internal static string ActivationSuccess_MSGCaption {
            get {
                return ResourceManager.GetString("ActivationSuccess_MSGCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _-_Auth_-_.
        /// </summary>
        internal static string AuthCode {
            get {
                return ResourceManager.GetString("AuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIHub_2017Q1_0314_en.
        /// </summary>
        internal static string AuthKey {
            get {
                return ResourceManager.GetString("AuthKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Area is Empty or Invalid, Please Try Again..
        /// </summary>
        internal static string EmptyArea_MSGBody {
            get {
                return ResourceManager.GetString("EmptyArea_MSGBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Error_Caption {
            get {
                return ResourceManager.GetString("Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll be notified again when you start the app again to activate....
        /// </summary>
        internal static string ExitButton_MSGBody {
            get {
                return ResourceManager.GetString("ExitButton_MSGBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Canceled!.
        /// </summary>
        internal static string ExitButton_MSGCaption {
            get {
                return ResourceManager.GetString("ExitButton_MSGCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon1 {
            get {
                object obj = ResourceManager.GetObject("icon1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Key is Incorrect, Please Try Again..
        /// </summary>
        internal static string IncorrectKey_MSGBody {
            get {
                return ResourceManager.GetString("IncorrectKey_MSGBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Directory doesn&apos;t Exist, Please Contact CDAGaming..
        /// </summary>
        internal static string IncorrectKeyFile_MSGBody {
            get {
                return ResourceManager.GetString("IncorrectKeyFile_MSGBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Montserrat_Regular {
            get {
                object obj = ResourceManager.GetObject("Montserrat_Regular", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This App Uses the Following Font: Montserrat-Regular. Would you like to Install this Font?.
        /// </summary>
        internal static string MSG_FontInstall_Body {
            get {
                return ResourceManager.GetString("MSG_FontInstall_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Installation.
        /// </summary>
        internal static string MSG_FontInstall_Caption {
            get {
                return ResourceManager.GetString("MSG_FontInstall_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;_&gt;.
        /// </summary>
        internal static string ReplacerKey {
            get {
                return ResourceManager.GetString("ReplacerKey", resourceCulture);
            }
        }
    }
}
